Divide the screen and add the menu
HT-Moh/mapbox pull request #9
Opened 2021-08-10 00:03 UTC by HTHoussam

On this commit i divided the screen vertically as you asked and added the menu to the top following task the folders and files structure given

2021-08-10 00:06 UTC, HTHoussam reviewed
I added some comments on my code as explanation

2021-08-10 00:06 UTC, HTHoussam commented on src/App.module.css
> +.split {
this is the css code responsible for dividing the screen

2021-08-10 00:06 UTC, HTHoussam commented on src/components/MapBoxJob.js
> +    width: "100%",
gave the map 100% width to fit inside the div

2021-08-10 00:06 UTC, HTHoussam commented on src/App.js
> +      <div className={`${classes.split} ${classes.right}`}>
this is the div rendered on the right of the screen contains map

2021-08-10 18:49 UTC, HT-Moh requested changes
I am not sure why do you need to add .split class 
You can use tailwindcss please check my other comment inline

2021-08-10 23:48 UTC, HTHoussam commented on src/App.js
> +      <div class='flex fixed w-full'>
I used tailwind to divide instead of css as requested

2021-08-11 11:09 UTC, HT-Moh reviewed
Good Job

2021-08-11 11:10 UTC, merged